theme: jekyll-theme-minimal

title: LopSae
description: Projects and Experiments.
logo: /assets/logo.png

show_downloads: false

defaults:
  - scope:
      path: "" # empty string includes all files
    values:
      layout: "ls-default"

lopsae:
  github-profile-url: https://github.com/lopsae